# Generated by Django 5.1.4 on 2024-12-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Ct', 'Central'), ('St', 'State')], max_length=2)),
                ('description', models.CharField(max_length=100)),
                ('beneficiaries', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='scheme_images')),
                ('region', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
