# Generated by Django 5.1.4 on 2024-12-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemes',
            name='type',
            field=models.CharField(choices=[('St', 'State'), ('Ct', 'Central')], max_length=2),
        ),
    ]
