# Generated by Django 5.1.4 on 2024-12-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_alter_schemes_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemes',
            name='region',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='schemes',
            name='type',
            field=models.CharField(choices=[('Ct', 'Central'), ('St', 'State')], max_length=2),
        ),
    ]
