# Generated by Django 5.1.4 on 2024-12-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0003_alter_schemes_region_alter_schemes_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemes',
            name='loan_type',
            field=models.CharField(default='gr', max_length=2),
            preserve_default=False,
        ),
    ]
