# Generated by Django 5.1.4 on 2024-12-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0004_schemes_loan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemes',
            name='loan_type',
            field=models.CharField(choices=[('re', 'Repayable'), ('gr', 'Grant')], max_length=2),
        ),
        migrations.AlterField(
            model_name='schemes',
            name='type',
            field=models.CharField(choices=[('St', 'State'), ('Ct', 'Central')], max_length=2),
        ),
    ]
