# Generated by Django 5.1.4 on 2024-12-11 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0005_alter_schemes_loan_type_alter_schemes_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_key', models.CharField(max_length=100)),
                ('criterion_value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Ct', 'Central'), ('St', 'State')], max_length=2)),
                ('description', models.TextField()),
                ('beneficiaries', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='scheme_images')),
                ('region', models.CharField(max_length=50)),
                ('loan_type', models.CharField(choices=[('re', 'Repayable'), ('gr', 'Grant')], default='re', max_length=2)),
                ('max_age', models.PositiveIntegerField(blank=True, null=True)),
                ('min_age', models.PositiveIntegerField(blank=True, null=True)),
                ('max_income', models.PositiveIntegerField(blank=True, null=True)),
                ('max_land_owned', models.FloatField(blank=True, null=True)),
                ('requires_aadhar_link', models.BooleanField(default=True)),
                ('requires_disability', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SchemeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('region', models.CharField(max_length=50)),
                ('annual_income', models.PositiveIntegerField()),
                ('disability', models.BooleanField(default=False)),
                ('employment', models.CharField(max_length=20)),
                ('unpaid_loans', models.BooleanField(default=False)),
                ('land_ownership', models.BooleanField(default=False)),
                ('land_owned', models.FloatField(default=0.0)),
                ('caste', models.CharField(max_length=20)),
                ('religion', models.CharField(max_length=20)),
                ('aadhar_link', models.BooleanField(default=False)),
                ('is_eligible', models.BooleanField(default=False)),
                ('validation_message', models.TextField(blank=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemes.scheme')),
            ],
        ),
        migrations.DeleteModel(
            name='Schemes',
        ),
        migrations.AddField(
            model_name='eligibilitycriteria',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='schemes.scheme'),
        ),
    ]
