# Generated by Django 5.1.4 on 2024-12-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=10)),
                ('ProductImage', models.ImageField(upload_to='subsidy_images/')),
                ('ProductPrice', models.IntegerField()),
                ('StockAvailability', models.BooleanField(default=True)),
                ('Category', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
